import type { Lead, BlogPost, Testimonial, AdminUser } from "@/types";

export const MOCK_LEADS: Lead[] = [
  {
    id: "lead-001",
    name: "Rico Manahan",
    email: "rico@grabph.com",
    mobile: "+63 917 234 5678",
    company: "Grab Philippines",
    useType: "fleet",
    productInterest: "TRIP Cargo Pro",
    quantity: 25,
    budget: "₱1.5M – ₱2M",
    contactMethod: "email",
    status: "qualified",
    score: 92,
    source: "Website Form",
    createdAt: "2026-07-01T09:30:00Z",
    updatedAt: "2026-07-03T14:00:00Z",
    assignedTo: "Carlos Reyes",
    followUpDate: "2026-07-08",
    notes: "Fleet manager for Grab Delivery. Very interested in bulk pricing and after-sales service.",
  },
  {
    id: "lead-002",
    name: "Maria Santos",
    email: "maria@foodpanda.ph",
    mobile: "+63 920 345 6789",
    company: "Foodpanda PH",
    useType: "fleet",
    productInterest: "TRIP Cargo Pro",
    quantity: 50,
    budget: "₱3M – ₱4M",
    contactMethod: "phone",
    status: "proposal",
    score: 98,
    source: "LinkedIn",
    createdAt: "2026-06-28T11:00:00Z",
    updatedAt: "2026-07-04T10:30:00Z",
    assignedTo: "Ana Lim",
    followUpDate: "2026-07-07",
    notes: "Head of Fleet Operations. Requesting formal proposal and financing terms.",
  },
  {
    id: "lead-003",
    name: "Jose Dela Cruz",
    email: "jose.dc@gmail.com",
    mobile: "+63 915 456 7890",
    useType: "personal",
    productInterest: "TRIP Fold X",
    quantity: 1,
    budget: "₱50K – ₱70K",
    contactMethod: "whatsapp",
    status: "new",
    score: 65,
    source: "Google Ads",
    createdAt: "2026-07-05T08:15:00Z",
    updatedAt: "2026-07-05T08:15:00Z",
    notes: "Interested for daily commute from Quezon City to BGC.",
  },
  {
    id: "lead-004",
    name: "Patricia Reyes",
    email: "pat.reyes@ncr.gov.ph",
    mobile: "+63 918 567 8901",
    company: "NCR Government",
    useType: "fleet",
    productInterest: "TRIP Ranger 750",
    quantity: 15,
    budget: "₱800K – ₱1M",
    contactMethod: "email",
    status: "negotiation",
    score: 88,
    source: "Referral",
    createdAt: "2026-06-20T13:45:00Z",
    updatedAt: "2026-07-04T16:00:00Z",
    assignedTo: "Carlos Reyes",
    followUpDate: "2026-07-09",
    notes: "Patrol unit fleet replacement. Budget approved, awaiting procurement process.",
  },
  {
    id: "lead-005",
    name: "Ben Tan",
    email: "ben@islandresort.ph",
    mobile: "+63 922 678 9012",
    company: "Palawan Island Resort",
    useType: "business",
    productInterest: "TRIP Fold X",
    quantity: 8,
    budget: "₱400K – ₱500K",
    contactMethod: "email",
    status: "contacted",
    score: 75,
    source: "Website Form",
    createdAt: "2026-07-02T10:00:00Z",
    updatedAt: "2026-07-03T09:30:00Z",
    assignedTo: "Ana Lim",
    followUpDate: "2026-07-10",
    notes: "Guest mobility solution for eco-resort. Interested in branded wraps.",
  },
  {
    id: "lead-006",
    name: "Danny Cruz",
    email: "danny@speedlogistics.ph",
    mobile: "+63 925 789 0123",
    company: "Speed Logistics Inc.",
    useType: "fleet",
    productInterest: "TRIP Cargo Pro",
    quantity: 30,
    budget: "₱1.8M – ₱2.5M",
    contactMethod: "phone",
    status: "closed_won",
    score: 100,
    source: "Trade Show",
    createdAt: "2026-06-10T14:00:00Z",
    updatedAt: "2026-06-25T11:00:00Z",
    assignedTo: "Carlos Reyes",
    notes: "Deal closed! 30 units delivered. Happy customer, follow up for maintenance.",
  },
  {
    id: "lead-007",
    name: "Lisa Park",
    email: "lisa@ateneo.edu.ph",
    mobile: "+63 927 890 1234",
    company: "Ateneo de Manila University",
    useType: "fleet",
    productInterest: "TRIP Fold X",
    quantity: 20,
    budget: "₱1M – ₱1.5M",
    contactMethod: "email",
    status: "new",
    score: 82,
    source: "Email Campaign",
    createdAt: "2026-07-05T11:30:00Z",
    updatedAt: "2026-07-05T11:30:00Z",
    notes: "Campus mobility program. Needs presentation to board of trustees.",
  },
];

export const MOCK_BLOG_POSTS: BlogPost[] = [
  {
    id: "blog-001",
    title: "Why E-Bikes Are the Future of Delivery in the Philippines",
    slug: "ebike-delivery-philippines-future",
    category: "Industry News",
    excerpt: "Discover how electric bikes are transforming last-mile delivery operations across Metro Manila and beyond, cutting costs by up to 80% compared to motorbikes.",
    content: "Full article content here...",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
    author: "TRIP Mobility Team",
    publishedAt: "2026-07-01",
    readTime: 6,
    tags: ["delivery", "e-bike", "Philippines", "logistics"],
  },
  {
    id: "blog-002",
    title: "Complete Guide: How to Choose the Right E-Bike for Your Needs",
    slug: "how-to-choose-ebike-philippines",
    category: "Buying Guide",
    excerpt: "From motor wattage to battery range — our expert guide helps you pick the perfect electric bike for your lifestyle or business needs in the Philippines.",
    content: "Full article content here...",
    image: "https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800&h=500&fit=crop",
    author: "TRIP Mobility Team",
    publishedAt: "2026-06-25",
    readTime: 8,
    tags: ["buying guide", "e-bike", "comparison"],
  },
  {
    id: "blog-003",
    title: "TRIP Mobility Partners with Major Food Delivery Platform",
    slug: "trip-mobility-delivery-partnership",
    category: "Company News",
    excerpt: "TRIP Mobility announces a strategic partnership to electrify delivery fleets nationwide, reducing carbon emissions and operational costs for riders.",
    content: "Full article content here...",
    image: "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=800&h=500&fit=crop",
    author: "TRIP Mobility Team",
    publishedAt: "2026-06-18",
    readTime: 4,
    tags: ["partnership", "fleet", "delivery"],
  },
  {
    id: "blog-004",
    title: "E-Bike Battery Care: Maximize Your Range and Lifespan",
    slug: "ebike-battery-care-guide",
    category: "Maintenance",
    excerpt: "Learn expert tips to extend the life of your TRIP e-bike battery and maintain peak performance through the Philippine climate.",
    content: "Full article content here...",
    image: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800&h=500&fit=crop",
    author: "TRIP Service Team",
    publishedAt: "2026-06-10",
    readTime: 5,
    tags: ["battery", "maintenance", "tips"],
  },
];

export const MOCK_TESTIMONIALS: Testimonial[] = [
  {
    id: "t-001",
    name: "Ramon Estrada",
    role: "Fleet Manager",
    company: "QuickBites Delivery",
    rating: 5,
    review: "We deployed 20 TRIP Cargo Pro units across Metro Manila. Our riders love them — the 100km range means no charging stops during peak hours. ROI in 4 months.",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ramon",
    product: "TRIP Cargo Pro",
  },
  {
    id: "t-002",
    name: "Carla Villanueva",
    role: "Operations Director",
    company: "IslaResort Palawan",
    rating: 5,
    review: "Our eco-resort guests absolutely love the TRIP Fold X bikes. The folding feature is perfect for our terrain, and the range handles all our island paths perfectly.",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=carla",
    product: "TRIP Fold X",
  },
  {
    id: "t-003",
    name: "Bernardo Reyes",
    role: "Chief of Patrol",
    company: "QC Local Government",
    rating: 5,
    review: "The Ranger 750 handles Quezon City's varying terrain effortlessly. Our patrol officers appreciate the power on inclines, and maintenance costs are minimal.",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=bernardo",
    product: "TRIP Ranger 750",
  },
  {
    id: "t-004",
    name: "Jennie Ocampo",
    role: "Daily Commuter",
    company: "Self-employed",
    rating: 5,
    review: "Switched from Grab rides to TRIP Fold X for my BGC to Makati commute. Saving ₱3,000 monthly on transport. Best investment I've made!",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=jennie",
    product: "TRIP Fold X",
  },
];

export const ADMIN_USERS: AdminUser[] = [
  {
    id: "u-001",
    name: "Miguel Torres",
    email: "miguel@tripmobility.ph",
    role: "super_admin",
    lastActive: "2026-07-06T08:00:00Z",
  },
  {
    id: "u-002",
    name: "Carlos Reyes",
    email: "carlos@tripmobility.ph",
    role: "sales_manager",
    lastActive: "2026-07-06T07:30:00Z",
  },
  {
    id: "u-003",
    name: "Ana Lim",
    email: "ana@tripmobility.ph",
    role: "sales_agent",
    lastActive: "2026-07-05T18:00:00Z",
  },
];

export const INDUSTRIES = [
  {
    id: "delivery",
    title: "Food & Package Delivery",
    icon: "Package",
    description: "Maximize rider income with 100+ km range. No fuel costs, zero maintenance downtime.",
    stat: "80% lower operating costs",
    color: "from-green-500/20 to-emerald-500/10",
  },
  {
    id: "corporate",
    title: "Corporate Mobility",
    icon: "Building2",
    description: "Branded fleet solutions for last-mile employee transport and campus mobility.",
    stat: "50+ enterprise clients",
    color: "from-cyan-500/20 to-blue-500/10",
  },
  {
    id: "government",
    title: "Government & Patrol",
    icon: "Shield",
    description: "Silent patrol units for law enforcement and municipal services across the Philippines.",
    stat: "Deployed in 12 LGUs",
    color: "from-yellow-500/20 to-orange-500/10",
  },
  {
    id: "tourism",
    title: "Tourism & Resorts",
    icon: "MapPin",
    description: "Eco-friendly guest mobility for resorts, hotels, and tourist destinations.",
    stat: "100+ resort partners",
    color: "from-purple-500/20 to-pink-500/10",
  },
  {
    id: "logistics",
    title: "Logistics & Courier",
    icon: "Truck",
    description: "Fleet-scale solutions with centralized maintenance and real-time GPS tracking.",
    stat: "30-unit minimum fleet",
    color: "from-red-500/20 to-rose-500/10",
  },
  {
    id: "education",
    title: "Universities & Schools",
    icon: "GraduationCap",
    description: "Campus mobility programs for students and staff with special institutional pricing.",
    stat: "20% education discount",
    color: "from-indigo-500/20 to-violet-500/10",
  },
];

export const FINANCING_OPTIONS = [
  {
    id: "starter",
    title: "Rider Starter",
    target: "Personal Use",
    downPayment: "20%",
    terms: "12–24 months",
    highlight: false,
    features: [
      "As low as ₱2,000/month",
      "No income proof for amounts below ₱100K",
      "Fast approval in 24 hours",
      "Free delivery Metro Manila",
    ],
  },
  {
    id: "fleet",
    title: "Fleet Pro",
    target: "5–50 Units",
    downPayment: "15%",
    terms: "24–36 months",
    highlight: true,
    features: [
      "Bulk pricing up to 15% off",
      "Dedicated account manager",
      "Free after-sales maintenance (1 year)",
      "GPS tracking included",
      "Branded wraps available",
    ],
  },
  {
    id: "enterprise",
    title: "Enterprise",
    target: "50+ Units",
    downPayment: "10%",
    terms: "36–60 months",
    highlight: false,
    features: [
      "Custom pricing negotiation",
      "Leasing options available",
      "On-site service team",
      "Extended 3-year warranty",
      "Priority spare parts access",
    ],
  },
];

export const SERVICE_CENTERS = [
  { city: "Metro Manila", address: "123 EDSA, Mandaluyong City", phone: "+63 2 8123 4567", hours: "Mon–Sat 8am–6pm" },
  { city: "Cebu City", address: "45 Colon Street, Cebu City", phone: "+63 32 234 5678", hours: "Mon–Sat 9am–5pm" },
  { city: "Davao City", address: "78 Claveria Street, Davao", phone: "+63 82 345 6789", hours: "Mon–Fri 9am–5pm" },
  { city: "Quezon City", address: "90 Commonwealth Ave, QC", phone: "+63 2 8234 5678", hours: "Mon–Sat 8am–6pm" },
];
